const tableName = 'students'

exports.seed = knex => {
  return knex(tableName).insert([
    { id: 1, preferred_name: 'Elizabeth', surname: 'Reeves', github_username: 'Elizabeth_Reeves', course_id: 1 },
    { id: 2, preferred_name: 'Karla', surname: 'Palmer', github_username: 'Karla_Palmer', course_id: 1 },
    { id: 3, preferred_name: 'Marlene', surname: 'Mendez', github_username: 'Marlene_Mendez', course_id: 1 },
    { id: 4, preferred_name: 'Mercedes', surname: 'Cook', github_username: 'Mercedes_Cook', course_id: 1 },
    { id: 5, preferred_name: 'Miriam', surname: 'Higgins', github_username: 'Miriam_Higgins', course_id: 1 },
    { id: 6, preferred_name: 'Ronald', surname: 'Fuller', github_username: 'Ronald_Fuller', course_id: 1 },
    { id: 7, preferred_name: 'Tracey', surname: 'Cannon', github_username: 'Tracey_Cannon', course_id: 1 },
    { id: 8, preferred_name: 'Joel', surname: 'Hudson', github_username: 'Joel_Hudson', course_id: 1 },
    { id: 9, preferred_name: 'Kristy', surname: 'Howell', github_username: 'Kristy_Howell', course_id: 1 },
    { id: 10, preferred_name: 'Sammy', surname: 'Reynolds', github_username: 'Sammy_Reynolds', course_id: 2 },
    { id: 11, preferred_name: 'Marjorie', surname: 'Wolfe', github_username: 'Marjorie_Wolfe', course_id: 2 },
    { id: 12, preferred_name: 'Lance', surname: 'Owen', github_username: 'Lance_Owen', course_id: 2 },
    { id: 13, preferred_name: 'David', surname: 'Stevenson', github_username: 'David_Stevenson', course_id: 2 },
    { id: 14, preferred_name: 'Wilson', surname: 'Austin', github_username: 'Wilson_Austin', course_id: 2 },
    { id: 15, preferred_name: 'Tammy', surname: 'Peterson', github_username: 'Tammy_Peterson', course_id: 2 },
    { id: 16, preferred_name: 'Hope', surname: 'Collier', github_username: 'Hope_Collier', course_id: 2 },
    { id: 17, preferred_name: 'Debra', surname: 'Rodriquez', github_username: 'Debra_Rodriquez', course_id: 2 },
    { id: 18, preferred_name: 'Bonnie', surname: 'Alexander', github_username: 'Bonnie_Alexander', course_id: 2 },
    { id: 19, preferred_name: 'Carol', surname: 'Kim', github_username: 'Carol_Kim', course_id: 3 },
    { id: 20, preferred_name: 'Cecelia', surname: 'Norton', github_username: 'Cecelia_Norton', course_id: 3 },
    { id: 21, preferred_name: 'Vera', surname: 'Estrada', github_username: 'Vera_Estrada', course_id: 3 },
    { id: 22, preferred_name: 'Olivia', surname: 'Dawson', github_username: 'Olivia_Dawson', course_id: 3 },
    { id: 23, preferred_name: 'Brooke', surname: 'Cruz', github_username: 'Brooke_Cruz', course_id: 3 },
    { id: 24, preferred_name: 'Grady', surname: 'Rodgers', github_username: 'Grady_Rodgers', course_id: 3 },
    { id: 25, preferred_name: 'Lela', surname: 'Gonzalez', github_username: 'Lela_Gonzalez', course_id: 3 },
    { id: 26, preferred_name: 'Luis', surname: 'Robertson', github_username: 'Luis_Robertson', course_id: 3 },
    { id: 27, preferred_name: 'Kelli', surname: 'Torres', github_username: 'Kelli_Torres', course_id: 3 },
    { id: 28, preferred_name: 'Florence', surname: 'Barnes', github_username: 'Florence_Barnes', course_id: 4 },
    { id: 29, preferred_name: 'Wilbur', surname: 'Wells', github_username: 'Wilbur_Wells', course_id: 4 },
    { id: 30, preferred_name: 'Constance', surname: 'Schultz', github_username: 'Constance_Schultz', course_id: 4 },
    { id: 31, preferred_name: 'Jackie', surname: 'Vega', github_username: 'Jackie_Vega', course_id: 4 },
    { id: 32, preferred_name: 'Walter', surname: 'McCarthy', github_username: 'Walter_McCarthy', course_id: 4 },
    { id: 33, preferred_name: 'Molly', surname: 'Ward', github_username: 'Molly_Ward', course_id: 4 },
    { id: 34, preferred_name: 'Celia', surname: 'Watson', github_username: 'Celia_Watson', course_id: 4 },
    { id: 35, preferred_name: 'Dora', surname: 'Herrera', github_username: 'Dora_Herrera', course_id: 4 },
    { id: 36, preferred_name: 'Eva', surname: 'Burton', github_username: 'Eva_Burton', course_id: 4 },
    { id: 37, preferred_name: 'Kelley', surname: 'Banks', github_username: 'Kelley_Banks', course_id: 4 },
    { id: 38, preferred_name: 'Doris', surname: 'Valdez', github_username: 'Doris_Valdez', course_id: 4 },
    { id: 39, preferred_name: 'Levi', surname: 'Frazier', github_username: 'Levi_Frazier', course_id: 4 },
    { id: 40, preferred_name: 'Marty', surname: 'Miles', github_username: 'Marty_Miles', course_id: 5 },
    { id: 41, preferred_name: 'Leo', surname: 'Jenkins', github_username: 'Leo_Jenkins', course_id: 5 },
    { id: 42, preferred_name: 'Monica', surname: 'Blair', github_username: 'Monica_Blair', course_id: 5 },
    { id: 43, preferred_name: 'Elaine', surname: 'Newman', github_username: 'Elaine_Newman', course_id: 5 },
    { id: 44, preferred_name: 'Dana', surname: 'Simpson', github_username: 'Dana_Simpson', course_id: 5 },
    { id: 45, preferred_name: 'Hattie', surname: 'Romero', github_username: 'Hattie_Romero', course_id: 5 },
    { id: 46, preferred_name: 'Natasha', surname: 'Lawson', github_username: 'Natasha_Lawson', course_id: 6 },
    { id: 47, preferred_name: 'Kyle', surname: 'Gonzales', github_username: 'Kyle_Gonzales', course_id: 6 },
    { id: 48, preferred_name: 'Kelly', surname: 'Graham', github_username: 'Kelly_Graham', course_id: 6 },
    { id: 49, preferred_name: 'Angie', surname: 'Nunez', github_username: 'Angie_Nunez', course_id: 6 },
    { id: 50, preferred_name: 'Armando', surname: 'Jones', github_username: 'Armando_Jones', course_id: 6 },
  ]).then(() => {
    return knex.raw(`SELECT setval('${tableName}_id_seq', (SELECT MAX(id) FROM ${tableName}));`)
  })
}
